name: 1. Test & Lint

on:
  workflow_call:
    inputs:
      source-sha:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Go fmt check
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "The following files need gofmt:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Build goCep binary
        run: go build -o goCep ./cmd/api

      - name: Upload goCep artifact
        uses: actions/upload-artifact@v4
        with:
          name: goCep-linux-amd64
          path: goCep
