name: 3. Scan Security

on:
  workflow_call:
    inputs:
      source-sha:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-sha }}

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: gocep-image

      - name: Load image metadata
        run: |
          set -euo pipefail
          source image-metadata.env
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"

      - name: Load Docker image
        run: docker load -i gocep-image.tar

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          output: trivy-report.txt
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
        continue-on-error: true
